name: bus_tracking_app
description: A real-time bus tracking application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  geolocator: ^10.0.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  # flutter_local_notifications: ^15.1.3  # Comment out this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 